# Generated by Django 5.0.6 on 2024-05-26 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='boost',
            field=models.FloatField(default=0, help_text='Boosts the article artificially', verbose_name='Boost Count'),
        ),
    ]
